name: Update Rockchip armv8 Workflow Inputs

on:
  push:
    paths:
      - 'immortalwrt_info.json'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure python3 & pyyaml
        run: |
          sudo apt update && sudo apt install -y python3-pip
          pip3 install pyyaml

      - name: Run workflow menu updater
        run: python3 .github/scripts/update_workflow_inputs.py

      - name: Create Pull Request for workflow update
        uses: peter-evans/create-pull-request@v7
        with:
          token:  ${{ secrets.WORKFLOW_WRITE_TOKEN }}
          commit-message: "chore: 自动更新 device_profiles 和 build_stability 选项 (来自 immortalwrt_info.json)"
          title: "chore: 自动更新 Rockchip armv8 workflow 设备/稳定性下拉菜单"
          body: |
            此 PR 由 bot 自动生成：同步 immortalwrt_info.json 变更，自动更新 .github/workflows/Rockchip armv8.yml 的下拉菜单内容。请审核合并，确保构建菜单永远保持最新支持设备。
          branch: "ci/update-workflow-inputs"
          base: main
          add-paths: .github/workflows/Rockchip\ armv8.yml
