name: Update Rockchip armv8 Workflow Inputs

on:
  push:
    paths:
      - 'immortalwrt_info.json'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure python3 is present
        run: sudo apt update && sudo apt install -y python3

      - name: Run profile and stability parser
        run: python3 .github/scripts/update_workflow_inputs.py

      - name: Patch Rockchip armv8.yml with new device_profiles and stability options
        run: |
          cp ".github/workflows/Rockchip armv8.yml" Rockchip_armv8.bak

          # 替换 device_profiles options
          awk '/device_profiles:/ {print;flag=1;next} flag && /options:/ {print;getline;while($0~/^ +-/){getline};flag=0;system("cat profile_options.txt");next} 1' Rockchip_armv8.bak > tmp1.yml

          # 替换 build_stability options
          awk '/build_stability:/ {print;flag=1;next} flag && /options:/ {print;getline;while($0~/^ +-/){getline};flag=0;system("cat stability_options.txt");next} 1' tmp1.yml > ".github/workflows/Rockchip armv8.yml"

      - name: Create Pull Request for workflow update
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: 自动更新 device_profiles 和 build_stability 选项 (来自 immortalwrt_info.json)"
          title: "chore: 自动更新 Rockchip armv8 workflow 设备/稳定性下拉菜单"
          body: |
            此 PR 由 bot 自动生成：同步 immortalwrt_info.json 变更，自动更新 .github/workflows/Rockchip armv8.yml 的下拉菜单内容。请审核合并，确保构建菜单永远保持最新支持设备。
          branch: "ci/update-workflow-inputs"
          base: main
          add-paths: .github/workflows/Rockchip\ armv8.yml